proj/accounts/urls.py
from django.urls import path

from .views import SignUpView
from .views import LoginView

urlpatterns = [
    #path("signup/", views.signup, name="signup"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(), name="login"),
]

proj/automodeler/urls.py
from django.urls import path

from . import views
from . import api
from . import engine_manager


urlpatterns = [
    path("", views.index, name="index"),
    path("automodeler/", views.index, name="automodeler"),
    path("upload/", views.upload, name="upload"),
    path("api/upload", api.api_upload, name="api_upload"),
    path("api/request_datasets", api.api_request_datasets, name="api_request_datasets"),
    path("api/request_models", api.api_request_models, name="api_request_models"),
    path("dataset_delete/<int:dataset_id>", views.dataset_delete, name="dataset_delete"),
    path("dataset/<int:dataset_id>", views.dataset, name="dataset"),
    path("dataset_details/<int:dataset_id>", views.dataset_details, name="dataset_details"),
    path("dataset_collection/", views.dataset_collection, name="dataset_collection"),
    path("update_selected_models/", views.update_selected_models, name="update_selected_models"),
    path("model_collection/", views.model_collection, name="model_collection"),
    path("model_details/<int:model_id>", views.model_details, name="model_details"),
    path("model_download/<int:model_id>", views.model_download, name="model_download"),
    path("model_delete/", views.model_delete, name="model_delete"),
    path("report_download/<int:dataset_id>", views.report_download, name="report_download"),
    path("task_collection/", views.task_collection, name="task_collection"),
    path("account/", views.account, name="account"),
    path("account_delete/", views.account_delete, name='account_delete'),
    path("ppe/start_preprocessing_request/", engine_manager.start_preprocessing_request, name="ppe"),
    path("mod/start_modeling_request/", engine_manager.start_modeling_request, name="ame"), # ame = automated model engine
    path("mod/run_model/", engine_manager.run_model, name="run_model"),
    path('check_task/<str:task_id>/', engine_manager.check_task_result, name='check_task_result'),
    #path('check_ppe_task/<str:task_id>/', engine_manager.check_preprocessing_task_result, name='check_preprocessing_task_result'),
    #path('check_run_model_task/<str:task_id>/', engine_manager.check_run_model_task_result, name='check_run_model_task_result')
]

proj/modelworx/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from automodeler.serializer import ModelWorxViewSet

router = routers.DefaultRouter() # Defining a router from the default rest framework router.
router.register('modelworx', ModelWorxViewSet, basename='modelworx') # Routing the serializer data to the modelworx path to be displayed.

urlpatterns = [
    path("automodeler/", include("automodeler.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include("accounts.urls")), # Used with middleware below
    #path('', include(router.urls)),
    path('', include("automodeler.urls")),
    path('logviewer/', include('logviewer.urls', namespace='logviewer')),
    path('two_factor/', include(('admin_two_factor.urls', 'admin_two_factor'), namespace='two_factor')),

]

proj/accounts/models.py
from django.db import models

# Create your models here.

class EmailTask(models.Model):
    TASK_TYPES = [
        ('emailing', 'Emailing'),
    ]

    task_id = models.CharField(max_length=255, unique=True)
    task_type = models.CharField(max_length=50, choices=TASK_TYPES)
    status = models.CharField(max_length=50, default='PENDING')
    result_message = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

proj/automodeler/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_delete
from django.dispatch import receiver

import os

# Create your models here.
class Dataset(models.Model):    
    FEATURE_LABELS = {
        'C': 'Categorical',
        'N': 'Numerical'
    }

    name = models.CharField(max_length=50)
    features = models.JSONField(default=dict, null=True)
    labeled = models.BooleanField(null=True)
    target_feature = models.CharField(max_length=50, null=True)
    csv_file = models.FileField(upload_to='dataset_uploads/')
    file_size = models.FloatField(null=True)
    number_of_rows = models.IntegerField(null=True)
    excluded_features = models.JSONField(default=dict, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def filename(self):
        return os.path.basename(self.csv_file.name)
    
    
    def save(self, *args, **kwargs):
        # If features has values in it, check that the labels are correct
        if not (self.features is None or not self.features):
            # If it's a list, there are not yet any categories
            if isinstance(self.features, list):
                self.labeled = False
                super().save(*args, **kwargs)
            else:
                if not isinstance(self.features, dict):
                    raise Exception("JSON was not a dictionary!")
                for key, value in self.features.items():
                    if value not in self.FEATURE_LABELS:
                        raise Exception("Unknown label found, not saving to database!")
                super().save(*args, **kwargs)
        
    
class PreprocessedDataSet(models.Model):
    MODEL_METHODS = {
        "LogisticRegression": "Logistic Regression",
        "RandomForestClassifier": "Random Forest Classifier",
        "GradientBoostingClassifier": "Gradient Boosting Classifier",
        "SVC": "SVC",
        "LinearRegression": "Linear Regression",
        "RandomForestRegressor": "Random Forest Regressor",
        "GradientBoostingRegressor": "Gradient Boosting Regressor",
        "SVR": "SVR"    
    }

    MODEL_TYPES = {
        "regression": "Regression",
        "classification": "Classification"
    }

    name = models.CharField(max_length=100)
    csv_file = models.FileField(upload_to='preprocessed_datasets/')    
    file_size = models.FloatField(null=True)
    number_of_rows = models.IntegerField(null=True)
    number_of_removed_rows = models.IntegerField(null=True)
    removed_features = models.JSONField(default=dict, null=True)
    model_type = models.CharField(max_length=15, choices=MODEL_TYPES, null=True)
    available_models = models.JSONField(default=list, null=True)
    selected_models = models.JSONField(default=list, null=True)
    feature_encoder = models.FileField(upload_to='pp_ds_bins/')
    scaler = models.FileField(upload_to='pp_ds_bins/')
    label_encoder = models.FileField(upload_to='pp_ds_bins/')
    meta_data = models.JSONField(default=dict)
    original_dataset = models.OneToOneField(Dataset, on_delete=models.CASCADE, blank=True, null=True)
    
    def filename(self):
        return os.path.basename(self.csv_file.name)
    
    def save(self, *args, **kwargs):
        # First, we need to validate that the available models are valid
        # Actually, what we need to do is set the list of available models
        if self.model_type == 'regression':
            self.available_models = [
                "LinearRegression",
                "RandomForestRegressor",
                "GradientBoostingRegressor",
                "SVR"
                ]
        elif self.model_type == 'classification':
            self.available_models = [
                "LogisticRegression",
                "RandomForestClassifier",
                "GradientBoostingClassifier",
                "SVC"
                ]
        #else:
        #    raise Exception('Invalid Model Type!')
        super().save(*args, **kwargs) # Call original save function to save to DB



class DatasetModel(models.Model):
    MODEL_METHODS = {
        "LogisticRegression": "Logistic Regression",
        "RandomForestClassifier": "Random Forest Classifier",
        "GradientBoostingClassifier": "Gradient Boosting Classifier",
        "SVC": "SVC",
        "LinearRegression": "Linear Regression",
        "RandomForestRegressor": "Random Forest Regressor",
        "GradientBoostingRegressor": "Gradient Boosting Regressor",
        "SVR": "SVR"    
    }
    
    MODEL_TYPES = {
        "regression": "Regression",
        "classification": "Classification"
    }
    
    name = models.CharField(max_length=100)
    model_file = models.FileField(upload_to='models/')
    model_method = models.CharField(max_length=30, choices=MODEL_METHODS)
    model_type = models.CharField(max_length=15, choices=MODEL_TYPES)
    tuned = models.BooleanField(null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    scores = models.JSONField(default=dict, null=True)
    original_dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)


class ModelingReport(models.Model):
    name = models.CharField(max_length=100)
    report_file = models.FileField(upload_to='reports/')  
    file_size = models.FloatField(null=True)
    original_dataset = models.OneToOneField(Dataset, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    
class TunedDatasetModel(models.Model):
    MODEL_METHODS = {
        "LogisticRegression": "Logistic Regression",
        "RandomForestClassifier": "Random Forest Classifier",
        "GradientBoostingClassifier": "Gradient Boosting Classifier",
        "SVC": "SVC",
        "LinearRegression": "Linear Regression",
        "RandomForestRegressor": "Random Forest Regressor",
        "GradientBoostingRegressor": "Gradient Boosting Regressor",
        "SVR": "SVR"    
    }
    
    MODEL_TYPES = {
        "regression": "Regression",
        "classification": "Classification"
    }
    
    name = models.CharField(max_length=100)
    model_file = models.FileField(upload_to='models/')
    model_method = models.CharField(max_length=30, choices=MODEL_METHODS)
    model_type = models.CharField(max_length=15, choices=MODEL_TYPES)
    untuned_model = models.OneToOneField(DatasetModel, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    original_dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    
    
class UserTask(models.Model):
    TASK_TYPES = [
        ('preprocessing', 'Preprocessing'),
        ('modeling', 'Modeling'),
        ('prediction', 'Prediction'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task_id = models.CharField(max_length=255, unique=True)
    task_type = models.CharField(max_length=50, choices=TASK_TYPES)
    status = models.CharField(max_length=50, default='PENDING')
    result_message = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE, null=True, blank =True)

@receiver(pre_delete, sender=Dataset)
def delete_usertasks_with_dataset(sender, instance, **kwargs):
    # Delete all UserTasks related to this dataset
    UserTask.objects.filter(dataset=instance).delete()

proj/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control'})
    )
    email = forms.EmailField(label="Email", widget=forms.EmailInput(
        attrs={'class': 'form-control'})
    )
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={'class' : 'form-control'})
    )
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(
        attrs={'class' : 'form-control'})
    )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        if commit:
            user.save()
        return user

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(
        attrs={'class': 'form-control'})
    )
    password = forms.CharField(label="Password", widget=forms.PasswordInput(
        attrs={'class' : 'form-control'})
    )

proj/automodeler/forms.py
from django import forms


class DatasetForm(forms.Form):
    name = forms.CharField(label="Dataset Name", max_length=50)
    #input_fields = forms.JSONField()
    #output_fields = forms.JSONField()
    csv_file = forms.FileField(allow_empty_file = False)

#class ParameterForm(forms.Form):

proj/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse

from .forms import UserRegisterForm
from .forms import UserLoginForm

from django.conf import settings

from .models import EmailTask
from .tasks import send_account_creation_email_task

class SignUpView(SuccessMessageMixin, CreateView):
  template_name = 'registration/signup.html'
  success_url = reverse_lazy('login')
  form_class = UserRegisterForm
  success_message = "Your profile was created successfully"

  def form_valid(self, form):
    # Save the form
    form.save()

    # Send email to admins
    email_enabled = settings.EMAIL_ENABLED
    if email_enabled:
      username = form.cleaned_data['username']
      email = form.cleaned_data['email']
      send_account_create_request_email(email, username)

    # Return the parent class' form_valid method
    return super().form_valid(form)


class LoginView(LoginView):
  template_name = 'registration/login.html'
  success_url = reverse_lazy('index')
  form_class = UserLoginForm



def send_account_create_request_email(useremail, username):
    # Launch celery task async
    async_results = send_account_creation_email_task.apply_async(args=[useremail, username])
    
    # Create UserTask
    email_task = EmailTask.objects.create( 
        task_id=async_results.id,
        task_type='emailing', 
        status='PENDING',
    )

    email_task.save() # Saving email to DB as ruff said it wasn't being used
    
    return JsonResponse({"task id": async_results.id})

  

proj/automodeler/templates/automodeler/account.html
{% include "base/header.html" %}
{% include "base/navbar.html" %}

<h1>Account Page - {{ user.username }}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p> {{ token }} </p>
    <input type="submit" value="Receive Token">
</form>

<br />

<a href="{% url 'account_delete' %}" class="btn btn-warning">Delete account</a>

{% include "base/footer.html" %}

proj/automodeler/templates/automodeler/account_delete_confirm.html
{% include "base/header.html" %}
{% include "base/navbar.html" %}


<h2>Are you sure that you wish to delete your account?</h2>
<br />
<h3>All of your associated datasets and models will be deleted</h3>
<form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Confirm Deletion</button>
</form>

{% include "base/footer.html" %}

proj/automodeler/templates/automodeler/dataset.html
{% include 'base/header.html' %}
{% include 'base/navbar.html' %}

<h1>Edit Dataset</h1>

<br />

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Table of Features</h3>
    <table class="table" id="id_dataset_cols_table" name="dataset_cols_table">
        <thead>
            <tr>
                <th scope="col">Features</th>
                <th scope="col">Target Variable</th>
                <th scope="col">Numerical (N) / Categorical (C)</th>
                <th scope="col">Exclude?</th>
            </tr>
        </thead>
        <tbody>
            {% for feature in dataset.features %}
            <tr>
                <td>{{ feature }}</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" value="{{ feature }}" type="radio" name="target_radio" id="id_io_radio_{{ feature }}">
                        <label class="form-check-label" for="id_io_radio_{{ feature }}"></label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="N" name="nc_radio_{{ feature }}" id="id_nc_radio1_{{ feature }}" checked>
                        <label class="form-check-label" for="id_nc_radio1_{{ feature }}">Numerical</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" value="C" name="nc_radio_{{ feature }}" id="id_nc_radio2_{{ feature }}">
                        <label class="form-check-label" for="id_nc_radio2_{{ feature }}">Categorical</label>
                    </div>
                </td>
                <td>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" name="exclude_check_{{ feature }}" id="id_exclude_check_{{ feature }}">
                    </div>
                </td>
            </tr>
            {% endfor %}        
        </tbody>
    </table>
    <input type="Submit" value="Submit"/>
</form>


{% include 'base/footer.html' %}

proj/automodeler/templates/automodeler/dataset_collection.html
{% include "base/header.html" %}
<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<!-- DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.3.1/css/dataTables.dataTables.css" />
<script src="https://cdn.datatables.net/2.3.1/js/dataTables.js"></script>


{% include "base/navbar.html" %}


{% if user.is_authenticated %}
<h1>Hello {{ user.username }}</h1>

{% if combined_datasets %}
<table class="table" id="id_datasets_table" name="datasets_table">
        <thead>
            <tr>
                <th scope="col">Dataset Name</th>
                <th scope="col">Dataset File Name</th>
                <th scope="col">Preprocessed Dataset</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for ds_list in combined_datasets %}
            <tr>
                <td>{{ ds_list.0.name }}</td>
                <td>{{ ds_list.0.filename }}</td>
                <td>
                    {% if ds_list.1 %}
                    {{ ds_list.1.filename }}
                    {% else %}
                    Dataset has not been preprocessed
                    {% endif %}
                </td>
                <td>
                    <a class="btn btn-warning" href="{% url 'dataset_details' dataset_id=ds_list.0.id %}">Details</a>
                    <button class="btn btn-primary" onclick="preprocess_fetch_request({{ ds_list.0.id }})">Start Preprocessing!</button>
                    <button class="btn btn-success" onclick="modeling_fetch_request({{ds_list.0.id }})">Start Modeling!</button>
                    <form method="post" action="{% url 'dataset_delete' dataset_id=ds_list.0.id %}">
                        {% csrf_token %}
                        <button class="btn btn-danger" type="Submit">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}        
        </tbody>
    </table>
{% else %}

<h2>User currently has no datasets</h2>

{% endif %}


<a href="{% url 'upload' %}" class="btn btn-primary">Upload dataset</a>

{% else %}
<h3>Not logged in</h3>
{% endif %}

{% include "base/footer.html" %}

<script>

function preprocess_fetch_request(dataset_id) {
    var url = '{% url 'ppe' %}';
    var CSRF_TOKEN = '{{ csrf_token }}';

    const row = document.querySelector(`button[onclick="preprocess_fetch_request(${dataset_id})"]`).closest('tr');
    const statusCell = row.children[2];
    statusCell.innerHTML = 'Processing... <span class="spinner-border spinner-border-sm text-primary" role="status"></span>';

    let formData = new FormData();
    formData.append("dataset_id", dataset_id)

    fetch(url, {
        method: 'POST',
        headers: {
            'X-CSRFToken': CSRF_TOKEN
        },
        body: formData
    })
    .then(response => {
        if (!response.ok) throw new Error(`HTTP error: ${response.status}`);
        return response.json();
    })
    .then(data => {
        pollTaskStatus(data.task_id, dataset_id);
    })
    .catch(error => {
        console.error('Fetch error:', error);
        statusCell.textContent = 'Failed to start preprocessing.';
    });
}

function pollTaskStatus(task_id, dataset_id, retries = 0) {
    fetch(`/automodeler/check_task/${task_id}/`)
    .then(response => {
        if (!response.ok) throw new Error(`HTTP error: ${response.status}`);
        return response.json();
     })
    .then(data => {
        if (data.status === 'PENDING') {
            if (retries < 30) {
                setTimeout(() => pollTaskStatus(task_id, dataset_id, retries + 1), 1000);
            } else {
                setStatusText(dataset_id, 'Timeout waiting for task');
            }
        } else if (data.filename) {
            // Task returned success result with filename
            updatePreprocessedCell(dataset_id, data);
        } else if (data.error) {
            setStatusText(dataset_id, data.error);
        } else {
            setStatusText(dataset_id, 'Unexpected task result');
        }
    })
    .catch(error => {
        console.error('Polling error:', error);
        setStatusText(dataset_id, 'Error checking task status');
    });
}

function setStatusText(dataset_id, text) {
    const row = document.querySelector(`button[onclick="preprocess_fetch_request(${dataset_id})"]`).closest('tr');
    const statusCell = row.children[2];
    statusCell.textContent = text;
}

function updatePreprocessedCell(dataset_id, result) {
    const row = document.querySelector(`button[onclick="preprocess_fetch_request(${dataset_id})"]`).closest('tr');
    const statusCell = row.children[2];
    statusCell.textContent = result.filename;
}

function modeling_fetch_request(dataset_id) {
    var url = '{% url 'ame' %}';
    var CSRF_TOKEN = '{{ csrf_token }}';

    let formData = new FormData();
    formData.append("dataset_id", dataset_id)

    fetch(url, {
        method: 'POST',
        headers: {
            'X-CSRFToken': CSRF_TOKEN
        },
        body: formData
    })
    .then(response => {
        if (!response.ok) {
            throw new Error(`HTTP error.  Status Code: ${response.status}`);
        }
        return response;
    })
    .then(responseData => {
        console.log('Response data:', responseData);
        window.location.reload()
    })
    .catch(error => {
        console.error('Fetch error:', error);
    })
}


$(document).ready( function () {
    $('#id_datasets_table').DataTable({
        searching: true
    });
} );

</script>

proj/automodeler/templates/automodeler/index.html
{% include "base/header.html" %}
<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<!-- DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.3.1/css/dataTables.dataTables.css" />
<script src="https://cdn.datatables.net/2.3.1/js/dataTables.js"></script>


{% include "base/navbar.html" %}



<div class="container">
    <h1>Welcome to Modelworx!</h1>
    <p>
        Modelworx is a tool developed as part of a project for Penn State University.  The intent of Modelworx is to provide automation
        for preprocessing datasets, and automatically building models from the scikit-learn Python package.  Modelworx as a tool will 
        attempt to determine the best model to be used for your dataset!  Additionally, Modelworx will create an URI endpoint that can be
        programatically utilized to run models remotely.  
    </p>
    <p>
        To get started, create an account, login, and then upload your first dataset!
    </p>
</div>


{% include "base/footer.html" %}

proj/automodeler/templates/automodeler/model_collection.html
{% include "base/header.html" %}
<!-- JQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

<!-- DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/2.3.1/css/dataTables.dataTables.css" />
<script src="https://cdn.datatables.net/2.3.1/js/dataTables.js"></script>


{% include "base/navbar.html" %}


<h1>Model Collection Page</h1>

{% if user.is_authenticated %}

{% if models %}
<table class="table" id="id_models_table" name="models_table">
        <thead>
            <tr>
                <th scope="col">Model Name</th>
                <th scope="col">Model Method</th>
                <th scope="col">Model Type</th>
                <th scope="col">Model Scores</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for model in models %}
            <tr>
                <td>{{ model.name }}</td>
                <td>{{ model.model_method }}</td>
                <td>{{ model.model_type }}</td>
                <td>
                    <ul>
                        {% for key, value in model.scores.items %}
                        <li>{{ key }} - {{ value }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a class="btn btn-primary" href="{% url 'model_details' model_id=model.id %}">View Details</a>
                    <form method="POST" action="{% url 'model_delete' %}">
                        {% csrf_token %}
                        <input type="hidden" name="model_id" id="model_id" value="{{ model.id }}"/>
                        <button type="Submit" class="btn btn-danger">Delete model</button>
                    </form>
                    <a class="btn btn-success" href="{% url 'model_download' model_id=model.id %}">Download Model</a>
                </td>
            </tr>
            {% endfor %}        
        </tbody>
    </table>
{% else %}

<h2>User currently has no models!</h2>
<br />
<h3>Models are available after uploading a dataset, preprocessing the dataset, and running the model engine!</h3>

{% endif %}

{% else %}
<h3>Not logged in</h3>
{% endif %}

{% include "base/footer.html" %}

<script>
    
function run_model_fetch_request(model_id) {
    var url = '{% url 'run_model' %}';
    var CSRF_TOKEN = '{{ csrf_token }}';

    let formData = new FormData();

    var data = {
        values: [
            1,
            2,
            3,
            4,
            "Iris-setosa"
        ]
    }
    var dataString = JSON.stringify(data)

    formData.append("model_id", model_id)
    formData.append("data", dataString)

    fetch(url, {
        method: 'POST',
        headers: {
            'X-CSRFToken': CSRF_TOKEN
        },
        body: formData
    })
    .then(response => {
        if (!response.ok) {
            throw new Error(`HTTP error.  Status Code: ${response.status}`);
        }
        return response;
    })
    .then(responseData => {
        console.log('Response data:', responseData);
        console.log('Response text:', responseData.text())
        //window.location.reload()
    })
    .catch(error => {
        console.error('Fetch error:', error);
    })
}

    $(document).ready( function () {
    $('#id_models_table').DataTable({
        searching: true
    });
} );

</script>

proj/automodeler/templates/automodeler/success.html
<h1>Upload successful!</h1>

proj/automodeler/templates/automodeler/upload.html
{% include "base/header.html" %}
{% include "base/navbar.html" %}

<h1>Dataset Upload Page</h1>


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<br/>
{% if err_msg %}
<h3>{{ err_msg }}</h3>
{% endif %}

{% include "base/footer.html" %}

proj/automodeler/templates/automodeler/upload2.html
{% include 'base/header.html' %}
{% include 'base/navbar.html' %}

<h1>Parameter Selection</h1>
<br />

<form method="POST" action="{% url 'save_dataset' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table" id="id_dataset_cols_table" name="dataset_cols_table">
        <thead>
            <tr>
                <th scope="col">Features</th>
                <th scope="col">Target Variable</th>
                <th scope="col">Numerical (N) / Categorical (C)</th>
            </tr>
        </thead>
        <tbody>
            {% for col in col_headers %}
            <tr>
                <td>{{ col }}</td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="target_radio" id="id_io_radio_{{ col }}">
                        <label class="form-check-label" for="id_io_radio_{{ col }}"></label>
                    </div>
                </td>
                <td>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="nc_radio_{{ col }}" id="id_nc_radio1_{{ col }}" checked>
                        <label class="form-check-label" for="id_nc_radio1_{{ col }}">Numerical</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="nc_radio_{{ col }}" id="id_nc_radio2_{{ col }}">
                        <label class="form-check-label" for="id_nc_radio2_{{ col }}">Categorical</label>
                    </div>
                </td>
            </tr>
            {% endfor %}        
        </tbody>
    </table>
    <input type="hidden" id="id_file_name" name="file_name">
    <input type="hidden" id="id_csv_file" name="csv_file">
    <input type="Submit" value="Submit"/>
</form>


{% include 'base/footer.html' %}